services:
  streamlit:
    build:
      context: ..
      dockerfile: ./ops/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ..:/app
    working_dir: /app
    command: streamlit run app.py
